# Generated by Django 2.1.7 on 2019-05-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('SourceURL', models.URLField(blank=True, null=True)),
                ('Servings', models.IntegerField()),
                ('Calories', models.FloatField(blank=True)),
                ('CaloriesServing', models.FloatField(blank=True)),
                ('Diet', models.CharField(choices=[('balanced', 'balanced'), ('high-protein', 'high-protein'), ('high-fiber', 'high-fiber'), ('low-fat', 'low-fat'), ('low-carb', 'low-carb'), ('low-sodium', 'low-sodium')], default='balanced', max_length=20)),
                ('Health', models.CharField(blank=True, choices=[('vegan', 'vegan'), ('vegetarian', 'vegetarian'), ('paleo', 'paleo'), ('dairy-free', 'dairy-free'), ('gluten-free', 'gluten-free'), ('wheat-free', 'wheat-free'), ('fat-free', 'fat-free'), ('low-sodium', 'low-sugar'), ('egg-free', 'egg-free'), ('peanut-free', 'peanut-free'), ('tree-nut-free', 'tree-nut-free'), ('soy-free', 'soy-free'), ('fish-free', 'fish-free'), ('shellfish-free', 'shellfish-free')], max_length=20)),
                ('Ingredient0', models.CharField(max_length=150)),
                ('Ingredient1', models.CharField(blank=True, max_length=150)),
                ('Ingredient2', models.CharField(blank=True, max_length=150)),
                ('Ingredient3', models.CharField(blank=True, max_length=150)),
                ('Ingredient4', models.CharField(blank=True, max_length=150)),
                ('Ingredient5', models.CharField(blank=True, max_length=150)),
                ('Ingredient6', models.CharField(blank=True, max_length=150)),
                ('Ingredient7', models.CharField(blank=True, max_length=150)),
                ('Ingredient8', models.CharField(blank=True, max_length=150)),
                ('Ingredient9', models.CharField(blank=True, max_length=150)),
                ('Instructions', models.TextField(blank=True)),
            ],
        ),
    ]
