#adapted from example in docker documentation
version: '3' 

services:

  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 8000:8000
    command: python /code/Django/recipe/manage.py runserver 0.0.0.0:8000
    links:
      - "redis:redis"

  redis:
    image: redis:2.8
    expose:
      - "6379"
