# Generated by Django 2.1.7 on 2019-03-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_Name', models.CharField(max_length=40)),
                ('Artist_Name', models.CharField(max_length=30)),
                ('Album_Name', models.CharField(max_length=30)),
                ('Song_Duration', models.CharField(max_length=5)),
                ('Release_Date', models.DateField()),
            ],
        ),
    ]
